services:
  mysql8:
    image: mysql:8.0
    restart: always
    container_name: bringit-mysql
    ports:
      - 3306:3306
    volumes:
      - bringit-mysql:/var/lib/mysql:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  backend-app-nest:
    image: backend-nest
    build:
      context: "$ROOT/backend-nest"
      dockerfile: "$ROOT/backend-nest/build/backend/Dockerfile"
    container_name: backend-app-nest
    env_file: "$ROOT/backend-nest/.env"
    volumes:
      - "$ROOT/backend-nest:/app:delegated"
    depends_on:
      mysql8:
        condition: service_healthy

volumes:
  bringit-mysql:
    name: bringit-mysql
    driver: local
